version: '3.4'

services:

  a:
    # Extend
    extends:
      file: docker-compose-a.yml
      service: app
    # Build override
    image: app-a

  b:
    # Extend
    extends:
      file: docker-compose-b.yml
      service: app
    # Build override
    image: app-b
    # Deploy override
    environment:
      SECRET: !reset null
    ports: !reset
      # HTTP
      - target: 80
        published: ${HTTP_B_PORT:-8080}
        protocol: tcp

  c:
    # Build
    image: app-c
    build:
      context: .
      dockerfile: Dockerfile
    # Deploy
    environment:
      APP_ENV: prod
      SECRET: ${SECRET:-secret}
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_C_PORT:-5000}
        protocol: tcp
