version: '3.4'

services:

  app:
    # Build
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    # Deploy
    environment:
      SECRET: ${SECRET:-secret}
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
